### ISSUE TITLE
End iterator on next error

### ISSUE THREAD

**Issue by vweevers** [Level/concat-iterator#1]
When used outside of tests, `concat-iterator` should call `.end` if there is a `next` error:

https://github.com/Level/concat-iterator/blob/9e62b4269efeffee1052cc84e7e31be243a35893/index.js#L8-L9

For example, when iterating an `encoding-down` iterator, `next` can call back with an `EncodingError`. If the underlying iterator is from `leveldown`, it should be ended.

**Comment by ralphtheninja** [comment]
I tried using this with `level` yesterday but couldn't get it to work. Something is fishy, either with this implementation or the iterator in `encoding-down`. Didn't look to much into it to avoid rabbit hole. But will check more today.

**Comment by vweevers** [comment]
> I tried using this

By this you mean `concat-iterator` in general or `concat-iterator` with end on error?

**Comment by ralphtheninja** [comment]
In general. It never called back with data, given the iterator from `encoding-down`.

**Comment by vweevers** [comment]
OK. Might be related to the `arguments` thing

**Comment by vweevers** [comment]
> Might be related to the arguments thing

Yup, that's it. So atm, there's two ways in the ecosystem to detect the end of iteration:

1. `arguments.length === 0`
2. `key === undefined && value === undefined`

We gotta pick one and stick with it.

**Comment by ralphtheninja** [comment]
I guess this should be specified in `abstract-leveldown` and the tests should enforce this. Right?

**Comment by ralphtheninja** [comment]
@vweevers WDYT about adding some abstract tests to `encoding-down`?

**Comment by vweevers** [comment]
Can't hurt!

**Comment by vweevers** [comment]
`level-iterator-stream` uses the key-value check:

https://github.com/Level/iterator-stream/blob/master/index.js#L28

**Comment by vweevers** [comment]
Ooh, and `level-iterator-stream` also doesn't end the iterator on an error.

**Comment by ralphtheninja** [comment]
> Ooh, and level-iterator-stream also doesn't end the iterator on an error.

Create issue please.
